help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

install: ## Install dependencies
	uv sync

run: ## Run the MCP server
	uv run python main.py

client: ## Run the MCP client
	uv run python client.py

dev: ## Launch the MCP Inspector against the server
	uv run mcp dev main.py:mcp

clean: ## Clean autogenerated files
	rm -rf dist
	rm -rf build
	rm -rf .pytest_cache
	rm -rf *.egg-info
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	rm -f .coverage
